<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>THRONES</title>
    <!--
    <link href="/css/app.css" rel="stylesheet" type="text/css">
    <script type="text/javascript" src="/js/app.js" charset="utf-8" async="async"></script>
     -->

    <link href="/res/libs/bootstrap-4.1.3-dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript" src="/res/libs/bootstrap-4.1.3-dist/js/bootstrap.min.js" charset="utf-8" async="async"></script>

    <link href="/res/libs/fontawesome-free-5.5.0-web/css/all.min.css" rel="stylesheet" type="text/css">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet" type="text/css">
  </head>


