<style>
#debugbar { position: fixed; z-index:2; bottom:0px; left: 0px; width:60px; background:#fafafa; border-top:solid 1px #ddd; }
#debugbar.active { width:100%; }

#debugbar div#debugbar-icon { position: relative; height:40px; line-height:40px; }
#debugbar div#debugbar-icon ul { list-style: none; padding: 0px; }
#debugbar div#debugbar-icon ul li { margin: 0px; padding: 0px; display: inline-block; }
#debugbar div#debugbar-icon ul li a { text-transform: capitalize;}

#debugbar div#debugbar-menus { display: none; position: absolute; left:10px; }
#debugbar.active div#debugbar-menus { display: block; }

#debugbar div#debugbar-body { display: none;	height:300px; background: #fff; padding:5px; border : solid 5px #eee; overflow: scroll; }

.debugbar-data-wrap { display:none; position: relative; }
.debugbar-data-popup { position: absolute; background:#fff; border: solid 3px #eee;padding:5px; }
</style>

<div id=debugbar class='active'>
	<div id='debugbar-icon'>
		<div style='position: absolute; right:10px;'>
			<a id='debugbar-toggle' href='javascript:void(0);' onclick="$('div#debugbar-body').toggle();"><span class='fa fa-chevron-up'></span></a>
			<a id='debugbar-close' href='javascript:void(0);' onclick="$('div#debugbar').toggleClass('active');"><span class='fa fa-times'></span></a>
		</div>

		<div id="debugbar-menus" class='active'> <!-- debugbar tab -->
			<ul>
				@foreach ( config('debugbar', 'items') as $type=>$config )
					@if ( ! $config['enable'] ) @continue @endif
					<li>
						<a class='btn btn-sm btn-default' href='javascript:void(0);' onclick="$('div.debugbar-content').hide(); $('#debugbar-{{ $type }}').show(); $('#debugbar-body').show();">
							<span class='{{ $config.css }}'></span>{{ $type }}
							<span class="badge badge-pill badge-dark">{@ $count = debugbar()->count($type) } @if ($count) {{ $count }} @endif</span>
						</a>
					</li>
				@endforeach
				<li><span class="fa fa-hashtag"></span></li>
				<li><span class="fa fa-clock"></span>Time: {@ echo debugbar()->totalTime() } Sec</li>
				<li><span class="fa fa-microchip"></span>Memory: {@ echo util()->unit()->auto( debugbar()->totalMemory() ) }</li>
			</ul>
		</div> <!-- debugbar tab -->
	</div>

	<div id='debugbar-body'> <!-- debugbar body -->
		@foreach ( config('debugbar', 'items') as $type=>$config )
			@if ( ! $config['enable'] ) @continue @endif
			<div id="debugbar-{{ $type }}" class='debugbar-content'>
				<h3 style='text-transform: uppercase;'>{{ $type }}</h3>

				@if (!empty($logs[$type]) )
				<div class='table-responsive-1'>{@ echo debugbar()->toHtml($logs) }</div>
				@endif
			</div>
		@endforeach
	</div> <!-- debugbar body -->

</div>