<script>
$(function(){
	// modalの表示
	$("a.load-to-modal").click(function(){
		let url = $(this).attr("href");
		$(".modal-title").text($(this).text());
		$("div.modal-body").html("<div style='margin: auto; text-align:center; vetical-align:middle;'><img src='/res/icons/loading.gif'></div>");
		$("div.modal-body").load(url);
	});

	// modal内の改ページアクション
	$("div.modal-body").on("click", "a.page-link",function(){
		let url = $(this).attr("href");
		$("div.modal-body").html("<div style='margin: auto; text-align:center; vetical-align:middle;'><img src='/res/icons/loading.gif'></div>");
		$("div.modal-body").load(url);
		return false;
	});
});
</script>

<div id=modal class="modal" tabindex="-1" role="dialog">
	<div class="modal-dialog" style="min-width:50vw; max-width: 90vw;" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Modal title</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body" style="min-height:50vh;"><p>Modal body text goes here.</p></div>
			<div class="modal-footer">
				<!-- <button type="button" class="btn btn-primary">Save changes</button> -->
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>
