<div class="sticky-top">
  <div class="thrones-box">
    <nav class="navbar navbar-expand-lg navbar-light bg-light ">
      <div class="container-fluid">
        <a class="navbar-brand thrones-logo" href="/admin/">PHP-PRESTO::local</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fa fa-cogs"></span>システム設定</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/admin/resource/index/"><span class="fa fa-database"></span>Resource一覧</a>
                <a class="dropdown-item" href="/admin/database/index/"><span class="fa fa-database"></span>DB一覧</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/admin/report/kpi/"><span class="fa fa-network-wired"></span>メンテナンス管理</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/admin/cstools/player/top/index/">システム情報</a>
                <a class="dropdown-item" href="/admin/cstools/player/top/index/">システム設定</a>
              </div>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="fa fa-th-list"></span>CSツール
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/admin/report/kpi/"><span class="fa fa-chart-bar"></span>KPI参照</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="/admin/cstools/player/top/index/"><span class="fa fa-user"></span>プレイヤー一覧</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#"><span class="fa fa-gift"></span>補填</a>
              </div>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="fa fa-spider"></span>デバッグ
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/admin/debugs/game/index/"><span class="fa fa-gamepad"></span>ゲーム</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="/admin/debugs/battle/index/"><span class="fa fa-shield-alt"></span>バトル</a>
              </div>
            </li>
          </ul>


          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fa fa-user-shield"></span>管理者</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/admin/profile/index/">プロフィル</a>
                  <div class="dropdown-divider"></div>

                  <a class="dropdown-item" href="/admin/auth/index/"><span class='fa fa-sign-in-alt'></span>LOGIN</a>
                  <a class="dropdown-item" href="/admin/auth/logout/"><span class='fa fa-sign-out-alt'></span>LOGOUT</a>
              </div>
            </li>
          </ul>

        </div>
      </div>
    </nav>
  </div>

  <div class="container-fluid">{@ breadcrumb()->show() }</div>
</div>